### OpenAI API
POST https://api.openai.com/v1/completions
Content-Type: application/json
Authorization: Bearer 토큰

{
  "model": "text-davinci-003",
  "prompt": "How to Kotlin?",
  "max_tokens": 1000,
  "temperature": 0.0,
  "top_p": 1
}
